8 recreate amm as substrate pallet
pendulum-chain/pendulum-amm pull request #16
Opened 2022-05-30 12:18 UTC by b-yap

This is faaar from finish, but just putting it out there so it's visible.

Things to do:
- [ ] add unit tests
- [ ] add mock
- [ ] add benchmark
- [ ] fix the weights
- [ ] fix the `unwrap()`s

Questions:
1.  What are these numbers: _`3`, `1000`, `997`_ ? ( example of [997]( https://github.com/pendulum-chain/pendulum-amm/pull/15/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R953)) I placed them as constants in the config. I'm thinking they must be defined at runtime. And they need proper names.
2. I have assigned the Balance and the Timestamp into different datatypes; the Timestamp derived from `pallet_timestamp`'s _`type Moment`_.  Now, that means it's incompatible to do any [calculation](https://github.com/pendulum-chain/pendulum-amm/pull/15/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R828) . 
And so that's the reason why I have added 1 more method (`fn moment_to_balance_type()`; I don't like the name at all, it can be changed) in the Extension trait and renamed from [BalanceExtension](https://github.com/pendulum-chain/pendulum-amm/blob/master/src/lib.rs#L11) to **_`AmmExtension`_** . 
I need your opinion about this.
3. It looks like substrate doesn't have `saturated_div()` ? I used the `checked_div()` instead. If none, it returns 0. 
Tell me if this is wrong, and if we should find another way.
4. The caller. I'm a little bit confused, especially on the `fn _swap()` and `fn burn()` with both having param: `to: AccountId`. 
Like [`fn swap_asset_1_for_asset_2()`... this function passes the `caller` to `fn _swap()`](https://github.com/pendulum-chain/pendulum-amm/pull/15/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R685). And [this is the same `caller` on the event being emitted inside `fn _swap()`](https://github.com/pendulum-chain/pendulum-amm/pull/15/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R773). So it's both Alice?

2022-05-31 14:32 UTC, ebma commented
Hey @b-yap. I will not do a full review of your changes yet, just try to answer some of your questions. 
Some parts of the code you see in #15 is not "ideal", i.e. it could probably be written more expressive and some things could be omitted/made easier with Rust. But I decided to stick pretty closely to the implementation of the solidity contracts that I linked to in #15. That's also where the "magic numbers" `3`, `1000`, and `997` are from. You can find more info in the [whitepaper](https://uniswap.org/whitepaper.pdf), for example I think section 3.2.1 is relevant for these numbers.
3. Are you sure you can't use `saturating_div`? It should be available on the u128 primitive (see [here](https://doc.rust-lang.org/std/primitive.u128.html)) 
4. This again is because I was sticking to their implementation. In the general case when executing e.g. a swap the caller and "destination"/`to` might be different but in our public convenience functions `swap_asset_x_for_asset_x_` we just assume the destination is the caller. 
6. Address zero is a destination that hopefully no account has access to that is used to lock some tokens permanently. Maybe we have to change it to something else.

I noticed that you renamed some things like the Events and function names. I understand your reasoning behind it because as I said some things are not super expressive but I think it would be better if the AMM smart contract and pallet use same names for 'identical' functions so that it's easier to understand and compare the two. The naming in #15 is based on the Uniswap interface so I would suggest we use that but if you have a strong opinion on this we can talk about it.

2022-06-01 08:29 UTC, ebma commented
I see. Well in theory we can just add a local function that does it, I found the related code in the rust repository [here](https://github.com/kellerkindt/rust/blob/master/library/core/src/num/int_macros.rs#L1071). But for that, you would need overflowing operations and I'm not sure if you have those? But I think we would need them anyways because the `_update()` functions uses an `overflowing_add()`.

2022-06-02 05:40 UTC, b-yap commented
@ebma , yes there's no overflowing operations too, :sweat:

Also, is it okay if I change from
```
pub type AssetCode = [u8; 12];
pub type IssuerId = [u8; 32];
```

to `CurrencyId` ? That way The `CurrencyId` defined in the runtime can be reused.

This means that these2 functions:
```
#[ink(message)]
		pub fn asset_1(&self) -> String {
			String::from_utf8(trim_zeros(&self.asset_1.1).to_vec()).unwrap()
		}

		#[ink(message)]
		pub fn issuer_1(&self) -> String {
			let issuer_1_encoded =
				encode_stellar_key(&self.asset_1.0, ED25519_PUBLIC_KEY_VERSION_BYTE);

			String::from_utf8(issuer_1_encoded).unwrap()
		}
```
Are now converted to 1: Just `Asset1`:
```
 #[pallet::storage]
    #[pallet::getter(fn asset_1)]
    pub(super) type Asset1<T:Config> = StorageValue<_,T::CurrencyId,OptionQuery>;
```

2022-06-02 15:36 UTC, ebma commented
The goal of the pallet was to be very similar to the smart contract. Now the problem is that while the smart contract AMM can be deployed for lots of different asset pairs on Pendulum, the pallet cannot (at least not that easily). To be precise, a substrate chain could actually have multiple copies of this pallet running for a different asset pair each, but I guess objectively this does not make much sense. I think generally speaking the optimal feature set of our pallet would be that it is able to create pools for different asset pairs and also offers function to interact with them. But since this would require additional efforts and make it different to what the smart contract AMM does, I would opt for keeping it in a state that one instance of this pallet only supports one asset pair and not multiple ones. Is that okay for you @prayagd?

2022-06-03 12:18 UTC, b-yap commented
:wave: :wave: @ebma @prayagd 

@gonzamontiel  and I had a sync call, and have decided to only support EUR/USDC pair. (for now)
I have moved its initialization(?)/declaration(?) [to the pallet config](https://github.com/pendulum-chain/pendulum-amm/pull/16/commits/88f2c4d3d80a876343389d7cbbd8d9aaad19adda#diff-0745aac8a9122df3f864fa8f72097995fc74848298eab2c7244e3d24b85a05d7R290-R291).

2022-06-07 08:13 UTC, ebma commented
@b-yap sorry I forgot to answer your question about the `CurrencyId`. I don't mind if you change it that way, it should not matter much.

2022-06-08 05:55 UTC, b-yap commented
@ashneverdawn the code is based on @ebma 's [branch](https://github.com/pendulum-chain/pendulum-amm/tree/6-add-missing-functions-of-uniswap-v2-pair-contract).

2022-06-08 09:57 UTC, b-yap commented
@erasmus I'm not good with documentation. This is what i came up with: https://github.com/pendulum-chain/pendulum-amm/blob/8-recreate-amm-as-substrate-pallet/pallet/README.md

2022-06-09 10:26 UTC, ebma requested changes
I tested the pallet and testchain in the polkadot.js app and everything seems to work as expected. Running the tests also worked for me. 

I left some comments and I want to agree on something for the magic numbers/variables first before approving. 

But you really did a great job @b-yap! :+1:

2022-06-09 10:26 UTC, ebma commented on pallet/src/lib.rs
> +		type SwapMulBalance: Get<Self::Balance>;
We should figure out something better for this. I'd actually opt for removing these from the config completely and hard-coding them but if you prefer having them configurable we should at least improve the names.

2022-06-09 10:26 UTC, ebma commented on pallet/src/helper.rs
> +		// * never overflows, and + overflow is desired
The way this works now, there is no overflow. But apparently in the original uniswap contracts they expect an overflow. I think in theory we could use plain Rust operations (`+`) instead of `checked_add` and it would wrap in release builds but it seems a bit unsafe to me. 
Let's maybe just add a FIXME comment pointing this issue out and figure it out later.

2022-06-09 10:26 UTC, ebma commented on pallet/src/tests.rs
> +		let reserves = reserves::<Test>();
I think this line can be removed?

2022-06-09 11:35 UTC, ebma commented on pallet/src/lib.rs
> +		type SwapMulBalance: Get<Self::Balance>;
I checked the [whitepaper](https://uniswap.org/whitepaper.pdf) again and I think we could rename `SwapMulBalance` to something like `BaseFee` because that's roughly what it is. But the value of "MulBalance" will always be 1000. The value of `SubFee` depends on `BaseFee` (see [whitepaper](https://uniswap.org/whitepaper.pdf) footnote 5 on page 5) but not in a simple way.

So since `SwapMulBalance` and `SubFee` depend on each other we would need to only make one specifiable and derive the other. But this makes it slightly more complex and since we are aiming for uniswap equivalence maybe it's okay if we stick to their values and hard-code all of the 4 variables.

2022-06-09 11:41 UTC, ebma approved these changes

2022-06-09 12:24 UTC, b-yap commented on pallet/src/lib.rs
> +		type SwapMulBalance: Get<Self::Balance>;
@ebma  is 1000 actually the minimum liquidity? 

> To mitigate this, Uniswap v2 burns the first 1e-15 (0.000000000000001) pool shares that
are minted (1000 times the minimum quantity of pool shares), sending them to the zero
address instead of to the minter.

https://jeiwan.net/posts/programming-defi-uniswapv2-1/
https://betterprogramming.pub/uniswap-v2-in-depth-98075c826254
https://docs.uniswap.org/protocol/V2/reference/smart-contracts/pair#minimum_liquidity

2022-06-10 05:04 UTC, b-yap commented on pallet/src/tests.rs
> +		let reserves = reserves::<Test>();
removed.

2022-06-10 05:04 UTC, b-yap commented on pallet/src/lib.rs
> +	pub(super) type ContractId<T: Config> = StorageValue<_, T::AccountId, OptionQuery>;
renamed

2022-06-10 05:05 UTC, b-yap commented on pallet/src/helper.rs
> +		// * never overflows, and + overflow is desired
i added as TODO.

2022-06-10 09:16 UTC, b-yap commented on pallet/src/helper.rs
> +		// * never overflows, and + overflow is desired
rust's `overflowing_add` doesn't seem to be complicated. The overflow value will always be **_addend - 1_.**
For `overflowing_sub`, the overflow value will always be the **_datatype::MAX - (subtrahend - 1)_**

2022-06-10 10:08 UTC, b-yap commented on pallet/src/helper.rs
> +		// * never overflows, and + overflow is desired
@ebma check https://github.com/pendulum-chain/pendulum-amm/pull/16/commits/629131197c3b94304a100199b476bba0f87cd516#diff-451ad90ce5e883c32e93bdc5e85119dd02e760efd1e4e7a2051535f71d995231R437-R469

2022-06-14 15:02 UTC, ebma commented on pallet/src/lib.rs
> +		type SwapMulBalance: Get<Self::Balance>;
Hmm yes seems like `1000` is actually the minimum liquidity. I need to change it in the AMM smart contract then because there we use the value of `1`.

2022-06-14 16:00 UTC, ebma requested changes
Everything looks good to me except the usage of MINIMUM_LIQUIDITY in places where a `1000` is needed. I added my reasoning to another comment but if you think it does not makes sense we can talk about it.

2022-06-15 04:42 UTC, b-yap commented on pallet/src/helper.rs
> +	let sub_fee = T::MinimumLiquidity::get() - T::BaseFee::get(); //expected to be 997
done,

2022-06-15 04:42 UTC, b-yap commented on pallet/src/helper.rs
> +		let sub_fee = T::MinimumLiquidity::get() - T::BaseFee::get(); // expected to be 997
done

2022-06-15 04:45 UTC, b-yap commented on pallet/src/helper.rs
> +	let multiplier_1000 = T::MinimumLiquidity::get();
done,

2022-06-15 04:45 UTC, b-yap commented
@ebma  Thanks for double checking!

I've updated the code based on your comments

2022-06-15 08:42 UTC, ebma commented on pallet/src/helper.rs
> +		_mint::<T>(&address_zero, T::MinimumLiquidity::get());
I changed this from the constant `1` to the actual value of minimum liquidity. But now the deposit doesn't work anymore, (see tests failing with `cargo test`)... Can you try to solve this @b-yap?

2022-06-15 09:24 UTC, b-yap commented on pallet/src/helper.rs
> +		_mint::<T>(&address_zero, T::MinimumLiquidity::get());
@ebma  for the test, is minimum liquidity = 1000 ? or minimum_liquidity = 1 ?

2022-06-15 10:55 UTC, ebma approved these changes

2022-06-15 11:23 UTC, merged